name: hoonar
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  hoonar_camera:
    path: "CameraPlugin/camera"

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  otp_pin_field: ^1.2.9+1
  carousel_slider: ^5.0.0
  chewie: ^1.8.5
  video_player: ^2.9.1
  smooth_page_indicator: ^1.2.0+3
  card_swiper: ^3.0.1
  flutter_animate: ^4.5.0
  flutter_html: ^3.0.0-beta.2
  audioplayers: ^6.1.0
  audioplayers_darwin: ^6.0.0
  flutter_video_info: ^1.3.2
  permission_handler: ^11.3.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_downloader: ^1.11.8
  ffmpeg_kit_flutter_full: ^6.0.3
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  fluttermoji: ^1.0.2
  crop_your_image: ^1.1.0
  camera: ^0.11.0+2
  photo_manager: ^3.5.0
#  camera: ^0.11.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/dark_mode_icons/
    - assets/light_mode_icons/


