name: hoonar
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.13+14


environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #  hoonar_camera:
  #      path: "CameraPlugin/camera"

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  otp_pin_field: ^1.2.9+1
  carousel_slider: ^5.0.0
  chewie: ^1.8.5
  video_player: ^2.9.1
  smooth_page_indicator: ^1.2.0+3
  card_swiper: ^3.0.1
  flutter_animate: ^4.5.0
  flutter_html: ^3.0.0-beta.2
  #  audioplayers: ^6.1.0
  audioplayers: ^5.2.0
  #  audioplayers_darwin: ^6.0.0
  flutter_video_info: ^1.3.2
  permission_handler: ^11.3.1
  #  intl: ^0.19.0
  intl: ^0.18.1
  image_picker: ^1.1.1
  #  flutter_downloader: ^1.11.8
  #  ffmpeg_kit_flutter_full: ^6.0.3
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  fluttermoji: ^1.0.2
  crop_your_image: ^1.1.0
  #  camera: ^0.11.0
  #  camera: ^0.11.0+2
  camera: ^0.10.5+2
  photo_manager: ^3.5.0
  get_it: ^8.0.0
  connectivity_plus: ^6.1.1
  dio: ^5.7.0
  flutter_async_autocomplete: ^0.1.1
  gradient_borders: ^1.0.1
  flutter_holo_date_picker: ^2.0.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.1.6
  device_info_plus: ^11.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  #  ve_sdk_flutter: ^0.9.0
  #  banuba_sdk: ^3.0.3
  #  face_camera: ^0.1.4
  visibility_detector: ^0.4.0+2
  swipe_to: ^1.0.6
  timeago: ^3.7.0
  url_launcher: ^6.3.1
#  google_mlkit_face_detection: ^0.12.0
  image_cropper: ^9.0.0
  image: ^4.3.0
  file_picker: ^9.0.1
  #  fijkplayer: ^0.11.0
  package_info_plus: ^8.1.1
  path_provider: ^2.1.5
  http: ^1.2.2
  ffmpeg_kit_flutter: ^6.0.3
  video_thumbnail: ^0.5.3
  flutter_sound: ^9.17.0
  flutter_audio_trimmer: ^0.0.5
  #  audio_waveforms: ^1.1.1
  flutter_audio_waveforms: ^1.2.1+8
  easy_audio_trimmer: ^1.0.2+4
  custom_social_share: ^1.0.9
  notification_permissions: ^0.6.1
  flutter_local_notifications: ^17.2.1+2
  flutter_local_notifications_linux: ^4.0.1
  upgrader: ^11.3.0
  retry: ^3.1.2
  lottie: ^3.2.0
  detectable_text_field: ^3.0.2
  razorpay_flutter: ^1.3.5
  location: ^6.0.2
  geocoding: ^3.0.0
  network_info_plus: ^6.1.2
  encrypt: ^5.0.3
  gif: ^2.3.0


  path: any
  flutter_branch_sdk: ^8.3.2
  facebook_app_events: ^0.19.4
#  firebase_analytics: ^11.4.4

dependency_overrides:
  intl: ^0.19.0
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/images/
    - assets/dark_mode_icons/
    - assets/light_mode_icons/
    - assets/lottie_json/


